# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Myles Rademaker"
resume_title:                   "Full Stack Developer"
resume_contact_email:           "mylesprademaker@gmail.com"
resume_contact_telephone:       "604-365-2188"
resume_contact_address:         "458 East 10th Street, North Vancouver"
resume_header_contact_info: "458 East 10th Street, North Vancouver | 604-365-2188 | mylesprademaker@gmail.com"
resume_header_intro: "<p>Full stack developer with experience in a fast paced start up enviroment creating Facebook Messenger chatbots. After strengthening my problem solving skills and ability to put out an MVP in a timely manor I am looking for an enviroment to improve my code efficiency and maintainability. A strong worker who is comfortable within a team dynamic or working on my own. Always willing to receive feedback in order to improve my work or offer an opinion during team meetings. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mprads"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/myles-rademaker/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
